packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@reown/appkit': true
  bigint-buffer: set this to true or false
  bufferutil: true
  keccak: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
